### ISSUE TITLE
Redirect loop during checkout (checkout -> registration -> address -> registration)

### ISSUE THREAD

**Issue by ahx** [spree/spree_auth_devise#151]
I have a problem getting the master versions of spree and spree_auth_devise to work together. When being redirected to the registration page, i get stuck in a redirect loop.
I could not reproduce the issue when running the checkout feature spec, which run fine, but when running the app in development. 
Here's a plain simple example app (running Rails 4.0.2) to reproduce the error: https://github.com/ahx/spree_auth_devise_redirect_issue
You can find more details about all gem versions there.

I am seeing this error in Firefox 26 and Chrome 31.

Here are some parts of the log that illustrate the issue:

```
Redirected to http://localhost:3000/checkout/registration
Filter chain halted as :check_registration rendered or redirected
Completed 302 Found in 23ms (ActiveRecord: 1.7ms)
[…]
Started GET "/checkout/registration" for 127.0.0.1 at 2014-01-03 22:25:06 +0100
Processing by Spree::CheckoutController#edit as HTML
[…]
Redirected to http://localhost:3000/checkout/address
Filter chain halted as :ensure_valid_state rendered or redirected
Completed 302 Found in 14ms (ActiveRecord: 1.2ms)
[…]
Started GET "/checkout/address" for 127.0.0.1 at 2014-01-03 22:25:06 +0100
Processing by Spree::CheckoutController#edit as HTML
Parameters: {"state"=>"address"}
[…]
Spree::TokenizedPermission Load (0.2ms)  SELECT "spree_tokenized_permissions".* FROM "spree_tokenized_permissions" WHERE "spree_tokenized_permissions"."permissable_id" = ? AND "spree_tokenized_permissions"."permissable_type" = ? ORDER BY "spree_tokenized_permissions"."id" ASC LIMIT 1  [["permissable_id", 6], ["permissable_type", "Spree::Order"]]
Redirected to http://localhost:3000/checkout/registration
Filter chain halted as :check_registration rendered or redirected
Completed 302 Found in 106ms (ActiveRecord: 2.2ms)

Started GET "/checkout/registration" for 127.0.0.1 at 2014-01-03 22:25:06 +0100
Processing by Spree::CheckoutController#edit as HTML

Parameters: {"state"=>"registration"}
```

**Comment by saschagehlich** [comment]
I'm seeing this issue with `spree` 4.0.1 and `spree_auth_devise` 4.0.0, even though `spree_auth_devise` is beneath `spree` in Gemfile. Any hints?

**Comment by saschagehlich** [comment]
Just noticed that this was my fault, I'm overriding all of spree's routes and forgot to include the routes that spree_auth_devise is creating. Sorry!
