### ISSUE TITLE
Add Confirmable to User not working

### ISSUE THREAD

**Issue by coorasse** [spree/spree_auth_devise#170]
I added :confirmable to my user model and added relative columns in database.

First of all I had to override devise's email views because of the following error:

`undefined method 'spree_user_confirmation_url'`

in rendering confirmation email.

I replaced it with `spree.spree_user_confirmation_url(:confirmation_token => @token)`

and it works great but the generated URL: 

`http://localhost:3000/user/spree_user/confirmation?confirmation_token=ZSyGwYxNA_BcMw_zQfso` doesn't work at all saying
`uninitialized constant Spree::ConfirmationsController`

i tryied with

`http://localhost:3000/spree_user/confirmation?confirmation_token=ZSyGwYxNA_BcMw_zQfso` but doesn't work either saying `No route matches [GET] "/spree_user/confirmation"`

Any hint?

**Comment by Eileen0917** [comment]
Hi @coorasse,

I am doing same thing now.
I want to get confirmation token but my `@token` variable is nil.
Any hint?

Thanks.
