### ISSUE TITLE
Discussion: Splitting Spree Auth Devise into Several Gems

### ISSUE THREAD

**Issue by BenMorganIO** [spree/spree_auth_devise#246]
From #245.

Spree Auth Devise utilizes the frontend, backend, and core of Spree heavily. This issue is to discuss the possibility of splitting Spree Auth Devise into several gems for modularity.

cc @JDutil, @cbrunsdon

**Comment by JDutil** [comment]
@BenMorganIO was just discussing this with some other core members, and we're pretty much in agreement that the split would make sense.  We aren't really willing to put in the time and effort to make it happen though as the current implementation works fine for the majority of people.  If people would like to make the split into multiple components we would accept a PR for it, but don't have any immediate plans to implement ourselves as it's just not that high a priority for us.

**Comment by BenMorganIO** [comment]
@JDutil I was thinking the work would have to come from a PR. It would be a massive PR both in code changes and commits.

Can we set up a new branch for the split and I can provide smaller, sizeable PRs over time?

Also, when is Spree 3 due?

**Comment by JDutil** [comment]
I've created a new branch fix-246: https://github.com/spree/spree_auth_devise/tree/fix-246

There is no set timeline, but probably will be doing a release candidate in a week or two.

**Comment by JDutil** [comment]
Closing out as a question rather than an issue.
