### ISSUE TITLE
Gem version not consistent to branch name

### ISSUE THREAD

**Issue by fdelrio89** [spree/spree_auth_devise#258]
I'm trying to set up a new Spree store using spree version 2.3. I first create te rails project using rails 4.1.8.

Then, when I run `spree install --auto-accept`. I get this error message:
```
https://github.com/spree/spree_auth_devise.git (at 2-3-stable) is not yet checked out. Run `bundle install` first.
```

I then try to run `bundle install`, but everything looks fine.
But when I run  `bundle list` I get this:

    Using spree_auth_devise 2.2.0 from https://github.com/spree/spree_auth_devise.git (at 2-3-stable)

I check your gem version and they are not consistent with the branch name. For instance in the branch 2-3-stable, the gem version is set to 2.2.0.  I checked other spree gems and they are consistent.

Can this be my problem? I'm sorry if I miss some rules, this is my first time collaboration in any project here in github.

**Comment by JDutil** [comment]
Try running `bundle update` or remove spring from your gemfile as it's been causing issues.

The extension version numbers don't matter as we just use the stable branches.

**Comment by fdelrio89** [comment]
It work perfectly after removing spring! Thank you very much!
