### ISSUE TITLE
deleted_at column is missing in spree_users

### ISSUE THREAD

**Issue by kurapatijayaram** [spree/spree_auth_devise#271]
Hi
    In Spree::User model acts_as_paranoid was included . So, it expects deleted_at column in that table, that particular migration was missing. Pls add that migration.

Correct me if I was wrong ...

Thank u :-)

**Comment by JDutil** [comment]
https://github.com/spree/spree_auth_devise/blob/master/db/migrate/20140904000425_add_deleted_at_to_users.rb
