### ISSUE TITLE
Multiple user models 

### ISSUE THREAD

**Issue by kurapatijayaram** [spree/spree_auth_devise#281]
Hi,
     I created new user model using spree_auth_devise gem (not under spree module) for other purposes, everything is working fine under development environment but in production environment I am facing some issues with the spree current user session. I dont know why ?

Can anyone help me on this ....
Thank u.

**Comment by kurapatijayaram** [comment]
Hi, The above issue is because of eager load ..... I dont know why ?

**Comment by Alloffices** [comment]
did you figure this out > im wanting to do the same to my sample app but for some reason it dosent seem to work for me

**Comment by kurapatijayaram** [comment]
Hi @Alloffices , no I have to , but the problem is with eager loading . In development mode it's working fine
