### ISSUE TITLE
User seed - First and Last name missing validation error

### ISSUE THREAD

**Issue by crypticsymbols** [spree/spree_auth_devise#301]
Create the admin user (press enter for defaults).
Email [spree@example.com]: 
Password [spree123]: 
There was some problems with persisting new admin user:
First name can't be blank
Last name can't be blank

I'm happy to provide a PR if someone can confirm this isn't user error!

**Comment by JDutil** [comment]
You probably added a first and last name to your user model that your validating, but default seeding of users don't have first and last names.
