### ISSUE TITLE
Upgrade to Devise 3.5+

### ISSUE THREAD

**Issue by edmondchui** [spree/spree_auth_devise#316]
When will spree_auth_devise upgrade the Devise dependency to 3.5.6? The current dependency on Devise 3.4.1 is already over a year old.

https://github.com/plataformatec/devise/releases

**Comment by edmondchui** [comment]
One justification is that ```Confirmable#confirm!``` has been deprecated:

https://github.com/plataformatec/devise/blob/v3.5.4/lib/devise/models/confirmable.rb#L95-L98

**Comment by damianlegawiec** [comment]
Hi @edmondchui we'll be looking into upgrading to Devise 3.5+ for Spree 3.1 relase

https://github.com/spree/spree/wiki/Spree-Commerce-development-roadmap-2016

**Comment by damianlegawiec** [comment]
@edmondchui master is using Devise 3.5 now - https://github.com/spree/spree_auth_devise/pull/319

**Comment by edmondchui** [comment]
Thanks @damianlegawiec!
