### ISSUE TITLE
`Missing host to link to` when creating user in test mode

### ISSUE THREAD

**Issue by scan** [spree/spree_auth_devise#325]
Hello,

I'm using `spree_auth_devise` on branch `3-0-stable`. When I try to create a user using a factory like so

```ruby
factory :user, class: Spree::User do
  email Faker::Internet.safe_email
  password 'password'
  password_confirmation 'password'
end
```

I get the error 

```
ArgumentError:
       Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true
```

But only in test mode. I have triple checked this error, as it is a common one, but the usual solution did not work. My `config/environments/test.rb`:

```ruby
Rails.application.configure do
  # [...]
  config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }
end
```

And I even did this to check if the setting is taken properly:

```ruby
RSpec.describe Spree::User, type: :model do
  before do
    puts Rails.application.config.action_mailer.default_url_options.to_yaml
    @user = FactoryGirl.create :user
  end
end
```

The output shows that the setting is in fact there, properly, but is ignored by the mailer:

```
---
:host: localhost
:port: 3000
```

I have absolutely no idea what I'm doing wrong here, and trying to find a solution only leads to the usual "Put this into your `test.rb`", which I did.

And also, it does work in `development` mode just fine. But as long as this is not resolved, I cannot run any tests.

**Comment by krzysiek1507** [comment]
@scan, have you got `confimable` enabled for user model? You have to create Spree::Store
`let!(:store) { create :store }`

https://github.com/spree/spree_auth_devise/blob/master/app/mailers/spree/user_mailer.rb#L10

**Comment by scan** [comment]
That's it! There has to be a store.

Thank you, @krzysiek1507

**Comment by delphaber** [comment]
You sirs, @krzysiek1507 and @scan, have saved my day (and my evening).
