### ISSUE TITLE
uninitialized constant Deface (NameError)

### ISSUE THREAD

**Issue by calvinl** [spree/spree_auth_devise#330]
due to this file: https://github.com/spree/spree_auth_devise/blob/master/app/overrides/auth_shared_login_bar.rb

I don't see Deface anywhere in the gemspec or Gemfile, has it been removed?

**Comment by damianlegawiec** [comment]
@calvinl Auth Devise depends on Spree Core which depends on Deface 

https://github.com/spree/spree/blob/master/core/spree_core.gemspec#L27

**Comment by calvinl** [comment]
@damianlegawiec Figured this one out. I can reproduce this in production environment, when `spree_backend` or `spree_frontend` is omitted from the Gemfile (i.e. spree as an API only). 

`deface` is `require`d by [frontend](https://github.com/spree/spree/blob/3-0-stable/frontend/lib/spree/frontend.rb) and [backend](https://github.com/spree/spree/blob/3-0-stable/backend/lib/spree/backend.rb), but not by `core` nor by `spree_auth_devise`.

This makes sense since there is nothing to deface if a frontend nor a backend is installed (rare use case, but can happen). 

Would it make sense to add a require to `deface` [here](https://github.com/spree/spree_auth_devise/blob/master/lib/spree_auth_devise.rb), or require deface in `spree_core`?

Happy to submit a pull request if appropriate.

Reproduce with the following Gemfile:
```
...
gem 'spree_core', '3.0.7'
gem 'spree_api', '3.0.7'
```

Then run:
```
RAILS_ENV=production bundle exec rails c
```

Produces this error:
```
/home/ubuntu/.gems/ruby/2.3.0/gems/spree_auth_devise-3.0.6/app/overrides/auth_shared_login_bar.rb:1:in `<top (required)>': uninitialized constant Deface (NameError)
```
