### ISSUE TITLE
Limit users sign in base on their role

### ISSUE THREAD

**Issue by ducnguyenhuy** [spree/spree_auth_devise#336]
Hi,

I'm sorry because this is question, not issue. I'm posting here because I did not find any answer at google group https://groups.google.com/forum/#!topic/spree-user/Rv3F5Xk43Uc. 

More information: I'm using version 3.0.5

Thanks.

**Comment by Mafi88** [comment]
Spree Auth Devise uses Devise, so you can limit login in the same way: http://stackoverflow.com/a/7255155/3712646
Your special condition would be check for role blogger.
