### ISSUE TITLE
undefined local variable or method `env' in production

### ISSUE THREAD

**Issue by DethonUSAL** [spree/spree_auth_devise#400]
Hello, 
I got this error (`undefined local variable or method 'env'`) in production when trying to get the states for a country in the stock location form. It comes from the metal_decorator.rb in this extension.
I solved it by using `request.env['warden'].user` instead of just `env['warden'].user` but I don't really know why this happens, so a bit of insight would be appreciated.

Also, this is only necessary in production, development mode worked fine without this change.

**Comment by GarPit** [comment]
+1. The same for me. @DethonUSAL, thanks for workaround
