### ISSUE TITLE
Missing 'coffee_script' dependency

### ISSUE THREAD

**Issue by gael-ian** [spree/spree_auth_devise#405]
Hello,

As it's required as soon as [line 4 in the main file of the gem](https://github.com/spree/spree_auth_devise/blob/dd6f20664fe1b501eec631d9efbe78a10dd0a9dd/lib/spree_auth_devise.rb#L4), I wonder why is not `coffee_script` part of the gem dependencies in [gemspec](https://github.com/spree/spree_auth_devise/blob/master/spree_auth_devise.gemspec#L22) ?

Thanks

**Comment by damianlegawiec** [comment]
@gael-ian rails automatically adds `coffee-rails` dependency to your app, but we're actually in the process of transforming all coffee files into plain JavaScript to drop this dependency altogether

**Comment by gael-ian** [comment]
Rails does not include `coffee-rails` if the app was generated with `rails new {name} --skip-coffee`. But if you're migrating out of Coffee Script, this won't be an issue for long.

Thanks for your answer.
