### ISSUE TITLE
Devise Syntax Error

### ISSUE THREAD

**Issue by luisenrike** [spree/spree_auth_devise#420]
I'm getting this error with the latest release (3.3.1) because it's using devise 4.3.0 https://github.com/spree/spree_auth_devise/blob/14ddc467777f36f4397c29cbe85641600f334975/spree_auth_devise.gemspec#L22 that is not compatible with ruby 2.5 https://github.com/plataformatec/devise/issues/4630. The master branch is using the fixed version of devise, can you do a release with that code?https://github.com/spree/spree_auth_devise/blob/fc4be460b7fa992fca5da5aa9a5a764c3d8573d6/spree_auth_devise.gemspec#L22

Error:
```
/.rvm/gems/ruby-2.5.0/gems/devise-4.3.0/app/controllers/devise/sessions_controller.rb:5: syntax error, unexpected '}', expecting keyword_end
..."devise.skip_timeout"] = true }
```

**Comment by damianlegawiec** [comment]
@luisenrike please run `bundle update spree_auth_devise` - version `3.3.3` which enforces `devise ` `~> 4.4.0` was pushed to RubyGems

**Comment by luisenrike** [comment]
Thanks 👍
