### ISSUE TITLE
No Way For Users To Re-send The Account Confirmation Email 

### ISSUE THREAD

**Issue by MatthewKennedy** [spree/spree_auth_devise#446]
Playing around with the settings I set ```Spree::Auth::Config[:confirmable] = true``` and then I found I could not log into my account because it was not confirmed, but could I find a way to re-send the account confirmation email for my account, essentially locking myself out. 

I had no choice but to disable this feature as customers who had previously signed up would face the same issue.

Additionally while trying to find a way to trigger a new account confirmation email I tried to reset my password, there was a flash message with a missing translation.

```translation missing: en.devise.user_passwords.spree_user.updated_not_active```

Hope this information is useful.

**Comment by c1495616js** [comment]
you can update database for existing users like this:

```
Spree::User.all.each do |u|
   u.confirm
 end
```
