### ISSUE TITLE
2-Factor Authentication

### ISSUE THREAD

**Issue by mrbiggred** [spree/spree_auth_devise#469]
Hello,

Is there any plans for Spree Auth Devise to support 2-Factor authentication?  Ideally using the Google Authenticator or similar code generator application.  Thank you.

**Comment by damianlegawiec** [comment]
Hey @mrbiggred you can combine `spree_auth_devise` with https://github.com/tinfoil/devise-two-factor to implement 2FA

**Comment by mrbiggred** [comment]
@damianlegawiec thank you for the suggestion.  I'll look into and let you know if I can get it to work.  One of the issues I'm facing is the client is currently on Spree 1.3.  We have plans to slowly upgrade them this year but it will take a while till we are caught up.
