### ISSUE TITLE
Spree Frontend controllers initialisation

### ISSUE THREAD

**Issue by ayoubmez96** [spree/spree_auth_devise#590]
- i was trying to use `Spree::UserPasswordsController` but i was surprised that the controller is not initialised
- actually I noticed that all the frontend controllers `spree_auth_devise/tree/main/lib/controllers/frontend/spree` are not initialised if i don't fave `spree_frontend` in my gemfile **( just for information putting spree_frontend in my gemfile fixed the problem )**
- The problem is i do not want to include `spree_frontend` in my application because it will enable so much stuff (routes etc...) that i i don't need

- **Solutions:**
  - overide all the frontend controllers in your application
  - include `spree_frontend` gem in your gemfile
  - overide this method https://github.com/spree/spree_auth_devise/blob/main/lib/spree/auth/engine.rb#L59 so it will enable what i 
 need without including the spree_frontend gem

- in my gemfile i have :

```
gem 'spree_core', '~> 4.6.0'
gem 'spree_api', '~> 4.6.0'
gem 'spree_backend', '~> 4.6.0'
gem 'spree_emails', '~> 4.6.0'
gem 'spree_i18n', '~> 5.3'
gem 'spree_gateway', '~> 3.10'
gem 'spree_auth_devise', '~> 4.6.0'
gem 'spree_api_v1'
```

**Comment by damianlegawiec** [comment]
Hmm if you want to use the frontend controllers, without the entire frontend... I would recommend copying them over to your app.
